url: "https://999-emergency.github.io/"
baseurl: ""
title: "999 Emergency"
lang: "en-GB"

collections:
  team:
    order:
      - lily.md
      - super.md
      - matt.md
      - internet.md
      - creator.md
      - german.md
      - sgm.md
  teams:
    # order:
    #   - management.md
    #   - development.md
    #   - moderation.md
