on:
  push:
    branches:
      - master

name: Page Deploy

jobs:
  build:
    name: Page Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Gem Dep Cache
        uses: actions/cache@v2
        id: gem-cache
        with:
          path: vendor/cache
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Dependencies
        run: (cat Gemfile.lock && (gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)") || gem install bundler) && bundler config set deployment 'true' && bundler install
      - name: Build Cache
        run: bundler cache
        if: steps.gem-cache.outputs.cache-hit != 'true'
      - name: Build Site
        run: bundle exec jekyll build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
