on:
  push:
    branches:
      - master

name: Page Deploy

jobs:
  build:
    name: Page Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo gem install bundler && bundler install --deployment
      - name: Build Site
        run: bundle exec jekyll build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
